bufferSize: 2048
language: cn
pages:
- content: 欢迎来到语音增强质量的主观评测。<br>请单击 [下页] 按钮。
  id: welcome
  name: 语音增强质量评测
  type: generic
- content: 分别播放“干净的”reference 和处理后的音频，然后以 reference 音频作为参照，对处理后的音频的质量进行打分（0 到 100之间）。<br><br><strong>注意：</strong>您可能需要为每个音频样本进行多个指标的打分，比如
    语音质量、背景噪声质量 和 整体音频质量。<br>语音质量 表示处理后的音频中<strong>语音信号</strong>的质量，<font color="red">而不关心背景噪声的部分</font>。<br>背景噪声质量
    表示处理后的音频中<strong>背景噪声</strong>的质量，<font color="red">而不关心语音信号的部分</font>。<br>整体音频质量
    表示处理后的音频的<strong>整体质量</strong>，即<font color="red">同时考虑语音和背景噪声</font>。<br><br><strong>在主观评测的过程中，直到测试结束之前，请不要关闭或重新加载此页面，否则进度将会丢失。</strong><br><br>请单击
    [下页] 按钮。
  id: explanation
  name: 测试介绍
  type: generic
- content: 这是和后面评测中您将听到的音频相似的一个语音样本。请根据它调整耳机的音量。<br><br><strong>在评测过程中，请使用耳机，并在相对安静的房间中进行听音。</strong>
  defaultVolume: 1.0
  id: Volume check
  stimulus: configs/resources/samples/clean/p232_001.wav
  type: volume
-
  - random
  - colors:
    - '#ED8C01'
    - '#007ACC'
    - '#2f9b5c'
    content:
    - 分别播放 reference 和处理后的音频，然后对处理后的音频的<font color="red">整体质量</font>进行评估，即其中的语音信号是否很好地保留（无失真），同时背景噪声也被很好地抑制。<br>伴随着强干扰性噪声，且高度失真的语音，相应的得分是
      0。几乎没有噪声，且无失真的语音，相应的得分是 100。<br><br><strong>注意：</strong>reference 音频可能也包含一定噪声，处理后的音频中如果噪声更小则更好。<br><br>
    - 分别播放 reference 和处理后的音频，然后<strong>仅</strong>对处理后的音频中的<font color="red">语音质量</font>进行评估，即其中的语音信号是否很好地保留（无失真）。<br>高度失真的语音，相应的得分是
      0。没有任何失真的语音，相应的得分是 100。<br><br><strong>注意：</strong>在评估 语音质量 分数时，请<u>不要将背景噪声考虑在内</u>。<br><br>
    - 分别播放 reference 和处理后的音频，然后<strong>仅</strong>对处理后的音频中的<font color="red">噪声质量</font>进行评估，即其中的背景噪声的质量情况。<br>强干扰性噪声，相应的得分是
      100。几乎无噪声，相应的得分是 0。<br><br><strong>注意(1)：</strong>在评估背景噪声质量 分数时，请<u>不要将语音信号的质量考虑在内</u>。<br><strong>注意(2)：</strong>请根据每段音频中噪声的<strong>相对于语音的音量</strong>（而非绝对音量）来对该样本进行打分，因为不同音频的绝对音量很可能是不完全相同的。
    createAnchor35: false
    createAnchor70: false
    enableLooping: true
    id: close_talk_M06_440C020J_PED_REAL
    metrics:
    - 整体音频质量
    - 语音质量
    - 背景噪声质量
    mustPlayAll: true
    mustViewAllTabs: true
    name: 语音增强质量评测 (1/10)
    randomize: true
    reference: ./configs/resources/samples/p232_001/mono_ref.wav
    response:
    -
      - 很好
      - 好
      - 较好
      - 较差
      - 差
    -
      - 无失真
      - 轻微失真
      - 较失真
      - 相当失真
      - 极度失真
    -
      - 强干扰噪声
      - 有一定干扰性
      - 有噪声但无干扰性
      - 轻微噪声
      - 几乎无噪声
    showConditionNames: false
    stimuli:
      d2former: ./configs/resources/samples/p232_001/mono_c1.wav
      dccrn: ./configs/resources/samples/p232_001/mono_c2.wav
      dprnn: ./configs/resources/samples/p232_001/mono_c3.wav
      metric+: ./configs/resources/samples/p232_001/mono_c4.wav
      mpset: ./configs/resources/samples/p232_001/mono_c5.wav
    type: multi_metric_mushra
  
- content: 评测结束，请输入您的<strong>名字</strong>，并单击 [提交结果] 按钮。
  id: finish
  name: 评测结束
  popupContent: 您的评测结果已被记录。感谢您的配合！
  questionnaire:
  - label: 名字
    name: name
    optional: false
    type: text
  showResults: true
  type: finish
  writeResults: true
remoteService: service/write.php
showButtonPreviousPage: true
showWaveform: true
stopOnErrors: true
testId: subjective_evalaution
testname: Subjective evaluation
